#!/bin/sh

# Certifica-se de que estamos na branch principal
if [ `git rev-parse --abbrev-ref HEAD` != "main" ]; then
  echo "Você deve estar na branch main para publicar no GitHub Pages."
  exit 1
fi

# Crie uma build do seu projeto React (certifique-se de que o comando esteja correto)
npm run build

# Crie um novo diretório chamado "docs" e mova os arquivos de build para ele
rm -rf docs
mv build docs

# Atualize o arquivo README.md para redirecionar para a página principal
echo "<meta http-equiv=refresh content=0;url=docs/index.html>" > README.md

# Adicione os arquivos modificados
git add docs README.md

# Faça um commit das alterações
git commit -m "Publicando no GitHub Pages"

# Faça o push das alterações para o GitHub
git push origin main
